import ollama from 'ollama';
import {ToolRegistry} from '../tools/ToolRegistry.js';
import type {Tool} from '../tools/Tool.js';
import {getOllamaModel} from '../config.js';
import {errorMessage, tryParseJson} from '../utils/json.js';
import 'dotenv/config';

// Prevent the agent from getting stuck in an endless tool-calling loop.
const MAX_TOOL_ROUNDS = 20;

// Limit how much tool output is sent back to the model.
// Large tool results can consume a lot of context and reduce model performance.
const MAX_TOOL_RESULT_CHARS = 12_000;

export class Agent {
  constructor(
    public name: string,
    public role: string,
    private toolRegistry: ToolRegistry,
  ) {}

  /**
   * Runs a task using the configured Ollama model.
   *
   * The agent can repeatedly call tools when necessary. After each tool call,
   * the result is added to the conversation and sent back to the model so it
   * can decide what to do next.
   */
  async run(task: string): Promise<string> {
    // Get the model configured for the application.
    const model = getOllamaModel();

    // Convert our internal Tool objects into the format expected by Ollama.
    const tools = this.toolRegistry.getAll().map((tool: Tool) => ({
      type: 'function' as const,
      function: {
        name: tool.name,
        description: tool.description,
        parameters: tool.parameters,
      },
    }));

    // Start the conversation with the agent's role and the user's task.
    const messages = [
      {
        role: 'system',
        content: `
                You are ${this.name}.
                Your role:
                ${this.role}
                Follow your role when completing tasks.
                Use available tools when they are useful.
                Do not invent tool results.
        `.trim(),
      },
      {
        role: 'user',
        content: task,
      },
    ];

    // A single task may require several rounds of model -> tool -> model calls.
    // Stop after MAX_TOOL_ROUNDS to prevent infinite loops.
    for (let round = 1; round <= MAX_TOOL_ROUNDS; round += 1) {
      let response;

      try {
        // Ask Ollama to decide what to do next.
        // The model may either return a normal text response or request one
        // or more tools to be executed.
        response = await ollama.chat({
          model,
          messages,
          ...(tools.length > 0 ? {tools} : {}),
        });
      } catch (error) {
        // Convert unknown errors into a readable Error message.
        throw new Error(`${this.name} failed to call the model "${model}": ${errorMessage(error)}`);
      }

      // Keep the model's response in the conversation so the next request
      // has the full context of what has already happened.
      messages.push(response.message);

      // Ollama returns tool_calls when the model wants to use a tool.
      // If there are none, the model has finished its task.
      const toolCalls = response.message.tool_calls ?? [];

      if (toolCalls.length === 0) {
        const content = response.message.content?.trim();

        // Return the model's response if it contains text.
        // Otherwise, provide a fallback message.
        return content && content.length > 0
          ? response.message.content
          : `${this.name} finished without a text response.`;
      }

      // Execute every tool requested by the model.
      for (const toolCall of toolCalls) {
        const toolName = toolCall.function.name;
        const tool = this.toolRegistry.get(toolName);

        // The model may request a tool that is not registered.
        // Report the error back to the model so it can potentially recover.
        if (!tool) {
          messages.push({
            role: 'tool' as const,
            content: `Error: tool "${toolName}" was requested but not found.`,
          });
          continue;
        }

        console.log(`Executing tool: ${toolName}`, toolCall.function.arguments);

        let result: string;

        try {
          // Execute the requested tool with the arguments generated by the model.
          result = await tool.execute(toolCall.function.arguments);
        } catch (error) {
          // Instead of stopping the entire agent, return the tool error to
          // the model as a tool result so it can decide how to proceed.
          result = `Error executing tool "${toolName}": ${errorMessage(error)}`;
        }

        // Prevent extremely large tool results from filling the model context.
        if (result.length > MAX_TOOL_RESULT_CHARS) {
          result = `${result.slice(0, MAX_TOOL_RESULT_CHARS)}\n...[truncated]`;
        }

        // Add the tool result to the conversation.
        // On the next round, the model can use this result to continue working.
        messages.push({role: 'tool' as const, content: result});
      }
    }

    // The agent reached the safety limit without producing a final response.
    throw new Error(`${this.name} exceeded the maximum of ${MAX_TOOL_ROUNDS} tool-call rounds.`);
  }

  /**
   * Runs a task where the expected result is JSON.
   *
   * If the model returns invalid JSON, the task is retried with an additional
   * instruction telling the model to return only valid JSON.
   */
  async runJson<T>(task: string, retries = 2): Promise<T> {
    // Keep the most recent response so it can be included in the retry prompt.
    let lastResponse = '';

    // retries = 2 means the task can be attempted 3 times in total:
    // the initial attempt plus two retries.
    for (let attempt = 0; attempt <= retries; attempt += 1) {
      // The first attempt uses the original task.
      // Later attempts include the invalid response and explicitly ask for
      // JSON-only output.
      const prompt =
        attempt === 0
          ? task
          : `${task}

          Your previous reply was not valid JSON.
          Return ONLY a JSON object. Do not wrap it in markdown.

          Previous reply:
          ${lastResponse}`;

      // Run the agent normally and capture its text response.
      lastResponse = await this.run(prompt);

      // Try to parse the response as the expected generic type T.
      const parsed = tryParseJson<T>(lastResponse);

      if (parsed.ok) {
        // Return the parsed JSON as soon as a valid response is received.
        return parsed.value;
      }
    }

    // All attempts failed to produce valid JSON.
    throw new Error(
      `${this.name} returned invalid JSON after ${retries + 1} attempts:\n${lastResponse}`,
    );
  }
}
